name: Create dev build

on:
  workflow_dispatch:
  push:
    branches:
      - "**" # matches every branch
      - "!main" # excludes master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: prepare-zip
        uses: ./.github/actions/release-zip

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepare-zip.outputs.zip-name }}
          path: ${{ steps.prepare-zip.outputs.zip-name }}.zip
